#modLoader = "javafml"
#loaderVersion = "[46,)"

modLoader="kotlinforforge"
loaderVersion="[4.10,)"

license = "MIT"
[[mods]]
modId = "netmusic"
version = "${file.jarVersion}"
displayName = "Net Music Mod"
authors = "C"
description = "A music player mod"

[[dependencies.netmusic]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.netmusic]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.2)"
ordering = "NONE"
side = "BOTH"
